### ISSUE TITLE
RangeError: Maximum call stack size exceeded inside connection.query.override

### ISSUE THREAD

**Issue by MihaelIsaev** [tshemsedinov/node-mysql-utilities#10]
Ниже пример кода, который через 3-4 тысячи вызовов приводит к RangeError: Maximum call stack size exceeded
Это делает либу абсолютно неюзабельной на продакшене.
Стоит только убрать

    mysqlUtilities.upgrade(connection);
    mysqlUtilities.introspection(connection);

как ошибка исчезает. Методом научного тыка было выяснено, что проблема где-то в районе 37 строки utilities.js

    var query = this.inherited(sql, values, function(err, res, fields) {

Пример

    var mysql = require('mysql');
    var mysqlUtilities = require('mysql-utilities');
    var poolSettings = {
        connectionLimit : 100,
        host: 'localhost',
        user: 'fansy',
        password: 'fansy',
        database: 'fansyDevelop',
        debug : false
    };
    var pool = mysql.createPool(poolSettings);
    var i = 0;
    var recursiveTask = function() {
        pool.getConnection(function(err, connection) {
            if (!err) {
                mysqlUtilities.upgrade(connection);
                mysqlUtilities.introspection(connection);
                connection.beginTransaction(function(err) {
                    if (!err) {
                        connection.release();
                        i++;
                        console.log("recursive task completed "+i);
                        recursiveTask();
                    } else {
                        console.log("Failed to start db transaction");
                    }
                });
            } else {
                console.dir({mysqlPoolErr:err});
                if (connection) {
                    connection.release();
                }
            }
        });
    }
    recursiveTask();

Мозг сломал в попытках пофиксить. Раз в 2-3 дня приложение падает(

**Comment by tshemsedinov** [comment]
Вы просто пытаетесь много раз к одному и тому же соединению сделать примеси upgrade и introspection. Соединения в пуле же идут по кругу, вот и случается утечка. Можно проверять, была ли уже примесь или еще нет, например так:
```JavaScript
if (!connection.where)  mysqlUtilities.upgrade(connection);
if (!connection.primary) mysqlUtilities.introspection(connection);
```

**Comment by MihaelIsaev** [comment]
Вы спасли мой день, теперь утечки нет!
Надеюсь кому-то моя ошибка поможет не наступать на те же грабли.
Спасибо!

**Comment by tshemsedinov** [comment]
Сделал встроенную проверку, не первый, кто попадается, я же не встроил пулы в библиотеку, так что, это типичная проблема, надеюсь, что это кому-то сэкономит время. Если честно, я уже исключил mysql из всех своих разработок и поддерживаю библиотеку, не запуская код на тестирование уже полтора года. Но люди говорят, оно работает.
