### ISSUE TITLE
Update mysql version from 2.5.x to 2.15.x

### ISSUE THREAD

**Issue by ffpaul** [tshemsedinov/node-mysql-utilities#15]
Hello,

Trying to use this module within AWS BeanStalk with AWS Linux 2017.9 and its included nodeJS 4.4.3 and during the npm install it fails to complete.

Tracked it down to the node-mysql-utilities module because it is listing mysql as a dependency, but restricted to mysql = 2.5.x.   The latest 2.5.5 mysql module requires bignumber=2.0.0 which is deprecated due to a critical bug -
 [https://github.com/MikeMcl/bignumber.js/issues/58](https://github.com/MikeMcl/bignumber.js/issues/58)

I've been able to update node-mysql-utilities dependency to mysql 2.15.x and things work ok on my local machine, but since npm install is running on the beanstalk, I can't inject my updated mysql dependency into mysql-utilities.

Can you update the mysql dependency of this module to something newer, like mysql 2.15.x?

**Comment by ffpaul** [comment]
Updated and it's now happily building, thanks!

**Comment by tshemsedinov** [comment]
I am going to refactor everything to new JS syntax, add CI, tests, etc.
