### ISSUE TITLE
Feature request: implement `queryRows` to return array of rows

### ISSUE THREAD

**Issue by ghuser** [tshemsedinov/node-mysql-utilities#51]
**Is your feature request related to a problem? Please describe.**
It would be nice implementing `queryRows`, to do what `queryRow` does, but returning array of rows instead.
(I guess the implementation would be close to `queryHash` but instead of returning object to return array of objects)

**Describe the solution you'd like**

e.g. 

```js
connection.queryRows(
  'SELECT * FROM Language',
  (err, rows) => {
    console.dir({ queryRows: rows });
  }
);
```

Output:

```
queryRows: [
{
  LanguageId: 1,
  LanguageName: 'English',
  LanguageSign: 'en',
  LanguageISO: 'en',
  Caption: 'English'
},
...
{
  LanguageId: 3,
  LanguageName: 'Russian',
  LanguageSign: 'ru',
  LanguageISO: 'ru',
  Caption: 'Русский'
}
]
```

**Describe alternatives you've considered**

**Additional context**

**Comment by tshemsedinov** [comment]
You can use `query` method for that:
```js
connection.query(
  'SELECT * FROM Language',
  (err, rows) => {
    console.dir({ queryRows: rows });
  }
);
```
